import type { Metadata } from "next"; // 导入Next.js的Metadata类型
import { Inter } from "next/font/google"; // 导入Google Fonts中的Inter字体
import "./globals.css"; // 导入全局样式

// 配置Inter字体的子集为拉丁字母
const inter = Inter({ subsets: ["latin"] });

// 定义页面的元数据，如标题和描述
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 根布局组件
 * @param {Readonly<{ children: React.ReactNode }>} props - 组件的props，包含子元素
 * @returns {JSX.Element} 包含子元素的HTML页面
 */
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}